### ISSUE TITLE
扫描线跑到边框外面了 vvLaserDrawable

### ISSUE THREAD

**Issue by Null8889** [jenly1314/ViewfinderView#1]

**Comment by jenly1314** [comment]
配合使用 `vvLaserDrawableRatio` 可修改扫描线的宽度比例。

**Comment by Null8889** [comment]
扫描线是跑到下边框之外了，drawImageScanner 忽略了图片本身的高度

**Comment by jenly1314** [comment]
> 扫描线是跑到下边框之外了，drawImageScanner 忽略了图片本身的高度 <com.king.view.viewfinderview.ViewfinderView android:id="@+id/viewfinderView" android:layout_width="match_parent" android:layout_height="match_parent" app:vvFrameColor="@color/white" app:vvFrameCornerColor="@color/white" app:vvFrameCornerSize="20dp" app:vvFrameCornerStrokeWidth="5dp" app:vvFrameLineStrokeWidth="0.1dp" app:vvFramePaddingBottom="300dp" app:vvFramePaddingLeft="40dp" app:vvFramePaddingRight="40dp" app:vvFramePaddingTop="190dp" app:vvFrameRatio="0.79" app:vvLabelText="@string/qrcode_tips" app:vvLabelTextColor="@color/white" app:vvLabelTextLocation="bottom" app:vvLabelTextPadding="30dp" app:vvLabelTextSize="17sp" app:vvLaserColor="@color/white" app:vvLaserDrawable="@mipmap/ic_zxing" app:vvLaserDrawableRatio="0.65" app:vvLaserMovementSpeed="2dp" app:vvLaserStyle="image" />

加个 `vvLaserLineHeight`  配合使用
