### ISSUE TITLE
如何得到ViewfinderView里面取景框的坐标和宽高

### ISSUE THREAD

**Issue by wyp315360007** [jenly1314/ViewfinderView#2]
请问，MLKit这个demo里面扫码的时候，二维码或者条形码已经出现在PreviewView里面但是还没有到取景框的时候就已经识别成功了。我想加一个判断，只有当进入取景框里面的时候才把扫描结果显示出来。这个时候需要知道ViewfinderView里面取景框的坐标和宽高才能实现。[https://github.com/javaherisaber/MLBarcodeScanner/tree/master](https://github.com/javaherisaber/MLBarcodeScanner/tree/master)，这个例子就可以做到，但是我想用你写的这个jenly1314.MLKit包才完成扫码功能，现在唯一的缺点就是还没进入取景框就已经识别出图像了。

**Comment by jenly1314** [comment]
先看下相关属性说明吧，由配置决定的；如果是默认配置，则着重看这两个：**vvFrameRatio**、**vvFrameGravity**

| 属性                        | 属性类型   | 默认值                                | 属性说明                                            |
|:---------------------------|:----------|:-------------------------------------|:------------------------------------------------|
| vvFrameWidth               | dimension |                                      | 扫描框宽度                                           |
| vvFrameHeight              | dimension |                                      | 扫描框高度                                           |
| vvFrameRatio               | float     | 0.625f                               | 扫描框与屏幕占比,当未设置扫描框的宽高时，使用占比来计算宽高                  |
| vvFrameLineStrokeWidth     | dimension | 1dp                                  | 边框线宽度                                           |
| vvFramePaddingLeft         | dimension | 0                                    | 扫描框左边的内间距                                       |
| vvFramePaddingTop          | dimension | 0                                    | 扫描框上边的内间距                                       |
| vvFramePaddingRight        | dimension | 0                                    | 扫描框右边的内间距                                       |
| vvFramePaddingBottom       | dimension | 0                                    | 扫描框下边的内间距                                       |
| vvFrameGravity             | enum      | center                               | 扫描框对齐方式                                         |

**Comment by wyp315360007** [comment]
> 先看下相关属性说明吧，由配置决定的；如果是默认配置，则着重看这两个：**vvFrameRatio**、**vvFrameGravity**
> 
> 属性	属性类型	默认值	属性说明
> vvFrameWidth	dimension		扫描框宽度
> vvFrameHeight	dimension		扫描框高度
> vvFrameRatio	float	0.625f	扫描框与屏幕占比,当未设置扫描框的宽高时，使用占比来计算宽高
> vvFrameLineStrokeWidth	dimension	1dp	边框线宽度
> vvFramePaddingLeft	dimension	0	扫描框左边的内间距
> vvFramePaddingTop	dimension	0	扫描框上边的内间距
> vvFramePaddingRight	dimension	0	扫描框右边的内间距
> vvFramePaddingBottom	dimension	0	扫描框下边的内间距
> vvFrameGravity	enum	center	扫描框对齐方式

通过反射的方式倒是得到ViewfinderView里面frame的rect值了，但是判断二维码的图片位置总是不在取景框内。呜呜
